### ISSUE TITLE
host turns into basePath

### ISSUE THREAD

**Issue by zeitlinger** [zalando/zally#1067]
the following patch fails with

```
org.junit.ComparisonFailure: 
Expected :"/host"
Actual   :"/basePath"
<Click to see difference>
```

@roxspring the reason for basePath is `de.zalando.zally.util.ast.JsonPointers#regexToReplacement` but I don't understand why `servers` should be translated to `basePath` rather than `host`

patch
```
Index: server/src/test/java/de/zalando/zally/rule/zalando/FunctionalNamingForHostnamesRuleTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- server/src/test/java/de/zalando/zally/rule/zalando/FunctionalNamingForHostnamesRuleTest.kt  (date 1569243428000)
+++ server/src/test/java/de/zalando/zally/rule/zalando/FunctionalNamingForHostnamesRuleTest.kt  (date 1571404509132)
@@ -1,6 +1,7 @@
 package de.zalando.zally.rule.zalando
 
 import de.zalando.zally.getOpenApiContextFromContent
+import de.zalando.zally.getSwaggerContextFromContent
 import de.zalando.zally.rule.api.Context
 import org.assertj.core.api.Assertions.assertThat
 import org.intellij.lang.annotations.Language
@@ -86,6 +87,27 @@
         assertThat(rule.mayFollowFunctionalNaming(context)).isEmpty()
     }
 
+    @Test
+    fun `host should return no violations `() {
+        @Language("YAML")
+        val context = getSwaggerContextFromContent(
+            """
+            swagger: '2.0'
+            info:
+              x-audience: company-internal
+            schemes:
+              - https
+            host: google.com
+        """
+        )
+
+        val violations = rule.shouldFollowFunctionalNaming(context)
+

```

**Comment by roxspring** [comment]
As indicated in the opening diagram of [A Visual Guide to What's New in Swagger 3.0](https://blog.readme.io/an-example-filled-guide-to-swagger-3-2/), when we upgrade a Swagger spec to OpenAPI we necessarily have to convert Swagger host, basePath, schemes into OpenAPI server constructs where the three are mangled into a url property. Once we've identified failures in these urls we need to then take the generated Violations and follow the conversion process in reverse, which we've implemented as a bunch of regex replacements. But in this case we have no way to know which component of the url the violation is referring to and therefore which original Swagger component to blame.

I suspect that we simply went with basePath because we had ExtractBasePathRule demonstrating the original problem (although [the original regex / replacement](https://github.com/zalando/zally/blame/ed8672454dfba770d68ccfdc167acf1f0ea2c675/server/src/main/java/de/zalando/zally/util/ast/JsonPointers.java) came from @mfellner @maxim-tschumak who might remember differently).

We have a couple of rules which only apply to Swagger (NoProtocolInHostRule, AtMostOneBodyParameterRule) and make use of the `context.swagger` property to do their checking. I think in this case the `FunctionalNamingForHostnamesRule` needs to do the same, performing a much simpler check against the host property only and crucially raising the violation against the correct structure without the regex replacement afterwards. The existing code to check `context.api` should only be used when processing OpenAPI 3.0.0 specs i.e. when `context.swagger==null`.

**Comment by zeitlinger** [comment]
@roxspring thanks for the explanation and the fix!

I was still at the point of trying to figure out why we can't always have the original reference to the offending line.
If I understand @tkrop correctly, this is caused by the swagger parser we use.

**Comment by roxspring** [comment]
No problem - was a good puzzle to finish a Friday on!

I agree it's a real shame that the original line numbers get thrown out by the underlying parser. I was pretty pleased with myself when I figured out the [hack](https://github.com/zalando/zally/blob/master/server/src/main/java/de/zalando/zally/rule/JsonPointerLocator.kt) to inject yaml line numbers after the fact but it's far from perfect.
