### ISSUE TITLE
Upgrade Java & Kotlin versions

### ISSUE THREAD

**Issue by vadeg** [zalando/zally#1085]
Upgrade Java to version 11 ([latest LTS](https://www.oracle.com/technetwork/java/java-se-support-roadmap.html)). 
Kotlin version requires upgrade as well in this case because current version `1.3.21` does not support 11 JVM target version.

The task can be split into three parts:
* [x] Upgrade Kotlin version to latest.
* [x] Upgrade Java version to `11`.
* [x] Change docker image from `registry.opensource.zalan.do/stups/openjdk:latest` to Java 11 image from [adoptopenjdk](https://hub.docker.com/r/adoptopenjdk/openjdk11).

**Comment by vadeg** [comment]
`dokka` version `0.10.0` does not work with Java 11. See Kotlin/dokka#294.

**Comment by roxspring** [comment]
Note that dokka is required for building the javadoc jar, which is a requirement of uploading to maven central, which was being worked on for #964. Given that work on uploading to maven central has stalled and publishing artifacts via JitPack appears to Just Work, then perhaps we should drop dokka & the javadoc jar rather than block an upgrade to Java 11?

**Comment by vadeg** [comment]
@roxspring I agree but I have some concerns about this. If I have a project which has a dependency from zally jar without javadoc but with sources will it appear correct in IDE's?

**Comment by roxspring** [comment]
Another thought: We could revert to the dokka html output rather than it's javadoc flavour for the javadoc jar - that [was our previous solution](https://github.com/zalando/zally/pull/979#issuecomment-484180751) before we [switched to the dokka javadoc content](https://github.com/zalando/zally/pull/1060).

**Comment by vadeg** [comment]
I think we can go with this:
> If, for some reason (for example, license issue or it's a Scala project), you can not provide -sources.jar or -javadoc.jar , please make fake -sources.jar or -javadoc.jar with simple README inside to pass the checking.

Taken from [here](https://central.sonatype.org/pages/requirements.html#supply-javadoc-and-sources). I am not sure what's the problem with Dokka. Sadly, but the bug is there for more than two years blocking normal deployment to OSS.

**Comment by vadeg** [comment]
Dokka is failing with OOM. 
Details are here: Kotlin/dokka#1405
