### ISSUE TITLE
User provided rule sets

### ISSUE THREAD

**Issue by digitalMLInc** [zalando/zally#1090]
Hi there,
To write my own rules to match my organisations API standards (and remove some existing rules I don't want), do I take the source code for the current release, write my own rules within the de.zalando.zally.rule.zalando/zally packages, then build and run?

This doesn't feel right - Is there a recommended way of editing existing rules/adding new rules for those outside of the Zalando organisation?

Thanks,
Ryan

**Comment by roxspring** [comment]
Yup. It's a little crazy but my company maintains an internal fork of Zally with our own custom rules and config added. There's some effort towards #551 leading towards #560 but it's slow progress - my motivation has dropped a little since the crazy internal fork approach is working well enough for my team.
