### ISSUE TITLE
How to pass "api_definition_string"

### ISSUE THREAD

**Issue by harinarayanan123** [zalando/zally#1091]
Hi Team,

Can you help me with a sample on how to pass the "api_definition_string" parameter in the **api-violations** call?

Thanks!

**Comment by roxspring** [comment]
Well, the API spec is [here](https://github.com/zalando/zally/blob/master/server/src/main/resources/api/zally-api.yaml) which hopefully makes some sense if you're into swagger/openapi 😄 

But the crux of it is that you need to POST a JSON structure to /api-violations, encoded as a string. So for example the following spec:

```yaml
openapi: "3.0.0"
info:
  version: 1.0.0
```

Would be encoded in a request as:

```json
{ "api_definition_string":"openapi: \"3.0.0\"\ninfo:\n  version: 1.0.0" }
```

Hope that helps, otherwise please give some examples of what you've tried.

**Comment by harinarayanan123** [comment]
Thanks @roxspring !
Let me give it a try and will let you know.

**Comment by harinarayanan123** [comment]
Many thanks @roxspring !!! It worked.
