### ISSUE TITLE
configuration to disable database

### ISSUE THREAD

**Issue by harpreet86** [zalando/zally#1106]
I am using zally but I don't want to use database, which means I do not want to create and run postgres image. Please suggest what all I need to configure for this. Thanks.

**Comment by roxspring** [comment]
There isn't a simple configuration to run without a database at the moment. The database is used to record validation history, and power the statistics endpoints and UI permalinks. Ideally, any configuration to run without the database at all would also disable the relevant API endpoints, and signal to the UI that permalink functionality should be hidden too.

Options that I think you have, ranging from ideal to lazy:

1. Open a pull request to add the functionality as described above.
2. The server already uses an internal database by default, so just let it do that and ignore the slow accumulation of memory (until it's cleared at restart). Essentially you'd need to remove the `SPRING_DATASOURCE_` prefixed environment variables from `docker-compose.yaml`.
3. Just let the bundled PostgreSQL run and ignore it (don't worry about requesting persistent storage). This is how we ran our internal Zally installation for the first year - occasionally our docker containers would be restarted and we'd lose history but nobody cared because permalinks weren't a thing and we weren't tracking statistics anyway. 😃 

Hope that helps!

**Comment by harpreet86** [comment]
Thanks, it helped. :)

**Comment by tkrop** [comment]
@harpreet86 unless you intend to contribute a patch I would like to close this issue. Or do you see a reason that requires to disable the in-memory database?

**Comment by vadeg** [comment]
Please reopen if still needed.
