### ISSUE TITLE
feat: allow compound keys in identifiers (#557)

### ISSUE THREAD

**Issue by tfrauenstein** [zalando/zally#1182]
Guideline PR https://github.com/zalando/restful-api-guidelines/pull/564 --> Zally Check needs to be updated

**Comment by vadeg** [comment]
Zally doesn't have the [Rule 228](https://opensource.zalando.com/restful-api-guidelines/#228). It can not effectively validate resource identifiers, because they are not available in the API definition, but only available in runtime. 
For the rest of changes Zally can not make any check, since the data is also available only online.

**Comment by tfrauenstein** [comment]
@vadeg [Rule 228](https://opensource.zalando.com/restful-api-guidelines/#228) is about syntax of resource ids and, yes, cannot be verified based on the API definition.  But the change of [Rule 143](https://opensource.zalando.com/restful-api-guidelines/#143) combined with new [Rule 241](https://opensource.zalando.com/restful-api-guidelines/#241) may require Zally check updates. Now, compound keys are allowed as path parameters, additionally to (sub-) resource ids.
