### ISSUE TITLE
Cannot use CLI against server with self signed SSL certificate

### ISSUE THREAD

**Issue by holgerstolzenberg** [zalando/zally#1185]
We are running a Zally server instance proxied by an Nginx VHost that also does the SSL offloading.
From our CI we try to run a Zally validation against this server using the CLI:

```bash
zally -l https://zally.theserver.org lint ./build/openapi.json
```
Causing this error:
```bash
Post "https://zally.theserver.org/api-violations": x509: certificate signed by unknown authority
```

As of now, it is not possible to skip the SSL validation.
Please add an argument for disabling the validation to the CLI (e.g. `--skip-ssl-validation`).

**Comment by tkrop** [comment]
@holgerstolzenberg Thanks for raising this issue. Seems not to be to difficult to implement, e.g. as described in https://github.com/minio/minio-go/issues/1019, however, validation is an essential step in communication security we are strongly interested in. Since we are lacking the resources (and priority) at the moment, we would welcome your contribution here and spend the time to review and test it.

**Comment by holgerstolzenberg** [comment]
Could you please give me fingerpointer in the code, where the SSL stuff sits, so that I can have a preliminary look at it before making any promises!?

**Comment by holgerstolzenberg** [comment]
Any plans when this is going to be releases?

**Comment by vadeg** [comment]
@holgerstolzenberg most probably next week
