### ISSUE TITLE
Consider using JDK-Standard 'ServiceLoader' instead of Spring

### ISSUE THREAD

**Issue by jbellmann** [zalando/zally#122]
... for loading rules into validator.

Hi Zally-Team, I would like you to consider using the ['ServiceLoader'-Feature](https://docs.oracle.com/javase/tutorial/ext/basics/spi.html) to load existing rules into the validator. Sure, I don't know what you plan for the future with Zally and how the Rules-interface will evolve in the future. From what I have seen so far, the ServiceLoader provided by the JDK can replace the existing mechanism to load the rules and the validator itself does not depend anymore on spring.

Removing the dependency to spring could make the validator more interesting for other projects. As an example [swagger-codegen-tooling](https://github.com/zalando-stups/swagger-codegen-tooling) comes into my mind. It would be a nice feature to validate the swagger.yaml before generating code.
Also for other integrations (Gradle-plugin) it would make sense to provide a validator with minimal dependencies.

Please have a look into the 'serviceloader'-branch to see how the 'ServiceLoader' can be used.

Regards
Jörg

**Comment by fmueller** [comment]
Wow, thanks for this interesting idea and proof of concept 👍 

You are totally right, without Spring integrations in other tools should be quite easy. For this we could fledge out the rule evaluation in a library and link this library to the server.

How could #75 be implemented with this approach? We'd like to make rule set configurable on runtime. As far as I understood your code, you have to provide the configuration in manifest file in META-INF.

**Comment by jbellmann** [comment]
Regarding #75 I could imagine to give every Rule-Implementation a unique id/shortname (think of modules/checks in [Checkstyle](http://checkstyle.sourceforge.net/checks.html)). Then after loading every rule available in classpath and picked up by ServiceLoader, just filter via standard 'java.util.function.Predicate<Rule>' and return a new RuleValidator-object containing only filtered rules. That would be the easiest thing to try first.

Which rules to include can be specified by a zally.yaml maybe of if nothing specified, every rule kicks in. In zally.yaml a 'include', 'exclude' section can exists to let the user define what makes sense for him/her.

For going with ids/shortnames it would helpful for a user to build then back-links to specific rules in the report (like in the checkstyle-link above). But I think I've seen something like that already, right?

Regards
Jörg

**Comment by mkulak** [comment]
Regarding #75 - I totally agree with @jbellmann, as long as we have full list of `Rule` implementations  we can filter it out by any criteria. 

Regarding ServiceLoader mechanism:
I've experimented with this approach.  It works fine but there is one substantial downside:
you need to explicitly list all your implementations in separate file (correct me if I'm wrong). Since in our case all implementations are known at compile time there is no value in it. You can simply write code like that:
```kotlin
val allRules = listOf(
  AvoidJavascriptKeywordsRule(),
  ExtractBasePathRule(),
  ...
)
```
(in fact first version of Zally worked exactly like that). Maintaining such list is proven to be tedious and error-prone in a long run.

If we want to move core validation logic into separate module that doesn't depend on Spring, I would suggest to use same mechanism as in Spring: classpath walking.
Possible implementation could be (reflections)[https://github.com/ronmamo/reflections] Perhaps we could even get rid of annotations and pick every class that implements Rule interface unless the class is marked with `@Ignore`.

**Comment by vadeg** [comment]
[AutoService](https://github.com/google/auto/tree/master/service) project can be used for generating config for `ServiceLoader` from source during compile. It use [java annotation processor](https://docs.oracle.com/javase/7/docs/api/javax/annotation/processing/Processor.html). Very easy to use. Very easy to implement. No dependency from Spring and no classpath walking at runtime.

**Comment by roxspring** [comment]
Given that:
1. #843 was rejected because it's "re-creating what Spring does already"
2. We make heavy use of Spring AOP in https://github.com/zalando/zally/blob/master/server/src/main/java/de/zalando/zally/util/ast/MethodCallRecorder.kt 

It appears that the switch to a Spring-free ServiceLoader mechanism is not happening and this issue can be closed.
