### ISSUE TITLE
Be compatible with OpenAPI 3.0

### ISSUE THREAD

**Issue by netme** [zalando/zally#204]
It's more an investigation task. Since OpenAPI 3.0 is on the way, we should be able to validate it as well.

## Possible steps
1. Check with API guild if we are ready with OpenAPI 3.0
2. Check if the existing swagger parsing libraries are compatible
3. Check the existing rules

Visual guide: https://blog.readme.io/an-example-filled-guide-to-swagger-3-2/

## Related Issues
- [ ] #714 Refactor Checks to Operate on the Context Object

**Comment by fmueller** [comment]
This depends on `swagger-parser`library I guess. So, we can contribute to this as well.

**Comment by netme** [comment]
Yes, also can be an option

**Comment by netme** [comment]
And now it's officially announced https://swagger.io/announcing-openapi-3-0/

 🎉

**Comment by innokenty** [comment]
I'm afraid we gonna have a dependency clash, in case we wanna import `swagger-models` maven artifact with the new api v3. It's not released yet, but it looks like the packages and class names are mostly the same: https://github.com/swagger-api/swagger-core/tree/feature/3.0.0-rc0/modules/swagger-models

Any ideas, how we wanna support v2 and v3 simultaneously in one process? Any **_r e p a c k a g i n g_** fans in the thread? 😃

**Comment by innokenty** [comment]
Wouldn't it be easier and nicer to split server into 3 modules: core, v2-validator and v3-validator? Running two instances of the server and having a simple switch in the UI, which validator to use.

**Comment by tkrop** [comment]
Shouldn't validation be based on the `swagger` header in the API specification? I would expect the parser to create a similar (or even same logical) model for both versions. Can we check whether we can update to the latest parser version that is able of parsing v2 and v3 and test some APIs?

I would like to announce that our tools are OpenAPI 3.0 compatible as soon as possible, and Zally seems to be the only unchecked application.

**Comment by netme** [comment]
@tkrop yes, we should do something like that. I will put this ticket as a priority then to check the status of the swagger parser we are using and keep you updated.

**Comment by fatroom** [comment]
@netme any news on this topic?

**Comment by netme** [comment]
@fatroom , sorry, we have abandoned this topic a bit. I will take a look on the latest `swagger-parser` implementation

**Comment by netme** [comment]
Looks like there is an official support of 3.0 which will be coming in `2.0` release. I will try to update my local branch to `2.0.0-rc1` to check if it's good enough, however we need to wait until the official release will be published.

**Comment by roxspring** [comment]
I believe that swagger-api 2.0 will parse contents into an OpenAPI 3.0 model and uses a separate package so that it doesn't clash with swagger-api 1.0 classes. 

Essentially I see two strategies that Zally could take in order to simultaneously support OpenAPI 2 and 3:
1. Parse 2.0 specs into 3.0, move the rules to use the 3.0 model, validate everything as if it's 3.0
2. Add duplicate rules (or possibly duplicate checks to existing rules) using parallel model objects.

The first makes me worry that we'll lose the distinction between 2.0 and 3.0 and it might be difficult if the two have slightly different semantics to enforce. The second concerns me because there'll end up being a ton of duplicate checks implemented with slightly different parameter types.

Do we have an idea which approach Zally intends to take?

**Comment by netme** [comment]
@roxspring thanks for checking this topic. I think you are talking about API schema validation rule here and it's quite a valid point. 

Let me discuss internally with @maxim-tschumak the API Team vision on this topic and then we might come with implementation strategy.

**Comment by maxim-tschumak** [comment]
Our strategy is to support OpenAPI 3.0 soon, preferably very soon :)

In the best case, swagger-parser 2.0 will support OpenAPI 2/3 and provide an OpenAPI 3-like API. In this case, we still have to update the checks, but we don't need to have multiple check implementation (per swagger version). I doubt that the same elements of OpenAPI 2 and 3 will have different semantics - Do you have an example @roxspring?

I would try to avoid multiple checks implementations. If swagger-parser will not be able to normalize OpenAPI 2. and 3. versions we should think about implementing our own parser.

**Comment by roxspring** [comment]
I haven't done a detailed investigation but a couple of differences jumped out at me:

1. Responses Objects in 2.0 are supposed to be keyed off "default" or a response code, but 3.0.0 also allows response code ranges. We don't have any rule validating this at the moment but if we did then it would need to be aware which spec is in use and therefore whether to reject "2XX" or not.
   - 2.0
     > Any HTTP status code can be used as the property name (one property per HTTP status code).
   - 3.0.0
     > Any HTTP status code can be used as the property name (one property per HTTP status code).
     > ...
     > To define a range of response codes, this field MAY contain the uppercase wildcard character X. For example, 2XX represents all response codes between [200-299].

2. Parameter Object's in 3.0.0 no longer allow "body" and "formData" parameters as support for these has moved and improved. Even if swagger-parser can conveniently load a 2.0 /paths/thepath/operation/parameters/parameter[in=body]/schema into a 3.0.0 /paths/thepath/operation/requestBody/content/"application/json"/schema then we'll end up reporting validation errors against the 3.0.0 location and potentially confuse 2.0 users.
   - 2.0
     > Possible values are "query", "header", "path", "formData" or "body".
   - 3.0.0
     > Possible values are "query", "header", "path" or "cookie".

I suspect that to support both specs as first class citizens then we ought to be maintaining parallel rule structures. Consequently I suspect that any attempt to reuse rules between specs is likely to relegate the older version to second class support. Not necessarily an evil or wrong outcome, but we should be aware of the potential pitfalls.

**Comment by roxspring** [comment]
Had a little play with swagger-parser-v3 and swagger-parser-v2-converter and confirmed:

- v3 and v2 models use separate namespace so can coexist
- v2 includes the same parser and model we're already used to

So I suspect we could quite easily:
- Add a new OpenAPIRuleValidator that will either parse v3 or parse v2 and convert to v3 model
- Move most/all rules to validate against the OpenAPI model and semantics
- Continue to support validation against Swagger model where any v2 specific semantics need to be validated
  - Possibly this might need to add extra logic so that a rule can implement both `validateSomething(Swagger)` and `validateSomething(OpenAPI)`, but we choose not to run the 2nd if the first was run (i.e. because the spec is v2). This way the same rule could enforce different semantics for v2 vs v3 specs if absolutely necessary.
- Presumably modify JsonRuleValidator to identify which schema to validate against

**Comment by mfellner** [comment]
Hi @roxspring, I just wanted to give you a heads up that a colleague and I are going to try and tackle this issue this week since we're having our annual "Hackweek". We'll probably try to just go down the convert-to-openapi3 route that you suggested and see what happens next.

**Comment by mfellner** [comment]
@vadeg and I looked further into the issue and decided it would be a good idea to implement https://github.com/zalando/zally/issues/689 (automatic JSON pointers) because it makes supporting both Swagger and OpenAPI3 objects inside rules much easier (we don't need to manually construct JSON pointers/paths for both versions).

**Comment by maxim-tschumak** [comment]
Done via #706
