### ISSUE TITLE
[EPIC] Zally Integration With GitHub Enterprise

### ISSUE THREAD

**Issue by netme** [zalando/zally#475]
## Acceptance criteria
*As* an API Developer
*I want* to get feedback on my API changes when I open Pull Request on GHE
*So* that I have an additional quality gate for the PR process

## Tickets
- #477 
- #478 
- #479 
- #480 
- #481 
- #482
- #483
- #484

## Target architecture
```
       On open PR                     Send validation request
                                       and store the result
GHE  <-------------> GHE Integration <-----------------------> ZALLY Server
          REST       (this project)            REST
```
## Workflow
1. Developer opens a PR on the `GitHub Enterprise` (`GHE`)
1. `GHE` via a Web-hook triggers  `GHE Integration Layer` (`IL`)
1. `IL` reads configuration of the repository
1. `IL` find Swagger file and send request to `ZALLY`
1. `IL` stores the validation result and notifies `GHE` back with the status and result link
1. By following the result link, Developer can always retrieve the validation result from `IL`

**Comment by roxspring** [comment]
I've recently been considering putting together a GitLab integration since that's our chosen SCM & CI system. Initial requirements would be very similar to these and so I was considering adding them to the existing project. All of which raises some questions:

1. Would you be interested in GitLab integration living within the Zally repo? (I suspect: yes)
2. Do you agree that it should live within the github-integration project (possibly renamed)?
3. Do people envision #484 involving the existing Web UI or an entirely new one?
4. If just one Web UI, does it really make sense for the integrations to run in a separate server?
5 Where does the project name `bark` come from??

**Comment by maxim-tschumak** [comment]
> Would you be interested in GitLab integration living within the Zally repo? (I suspect: yes)

Yes :)

> Do you agree that it should live within the github-integration project (possibly renamed)?

Yes

> Do people envision #484 involving the existing Web UI or an entirely new one?

I would integrate it into the existing Web UI.

> If just one Web UI, does it really make sense for the integrations to run in a separate server?

Yes, I would vote for clear separation of concerns.

> Where does the project name bark come from??

It's humor. And very funny. We have a dog in the Zally logo. And the dog [**barks**](https://en.oxforddictionaries.com/definition/bark) if there are any violations.

Please propose a new name if you think you have a better sense of humor. Functional naming always works for me.

**Comment by maxim-tschumak** [comment]
Agree. I'm just thinking if it makes sense for Zally server to be able to function without a persistence, in stand-alone mode. So that when there is no data source, Zally would disable permalinks and statistics features.

> (No objections to the name though - just hadn't spotted the joke)

It's german humor :)

**Comment by roxspring** [comment]
> when there is no data source, Zally would disable permalinks and statistics features.

That would have been a nice option to have for our first year - in-house the db just caused pain for us, largely because we didn't configure it well, as we weren't that interested in the stats. Now though, we've configured a stable db and are looking forward to permalinks and GitLab integration so can't see us disabling them in future.

**Comment by maxim-tschumak** [comment]
The same applies to us (low priority). It would be just a nice-to-have feature for any future users.

**Comment by vadeg** [comment]
@roxspring just to clarify: you are talking about **GitLab** integration or **GitHub**?

**Comment by roxspring** [comment]
Ultimately both. My personal motivation is around GitLab but the APIs etc are very close to those of GitHub so it would be crazy to implement them separately from each other, and personally seems suboptimal to implement either of them outside of Zally itself (particularly if #593 is done).

My ideal plan would be:
1. Implement permalinks directly in Zally #593 
2. Modify GitHub integration to use Zally permalinks
3. Move GitHub interation to Zally proper
4. Refactor and add GitLab support

I'm not in a position to really test changes to the GitHub integration so more likely I'll approach it:
1. Implement permalinks directly in Zally #593 
2. Implement GitLab integration directly in Zally, heavily inspired by existing GitHub integration code, but with the benefit of being able to test myself.
3. Move GitHub integration over to Zally too, asking a zalandonite to test the result.

**Comment by vadeg** [comment]
I haven't worked with GitLab API a lot but I have looked briefly on GitHub API and GitLab API and it looks similar (will skip about Merge Requests and Pull Requests :) )
For example, in GitHub [Checks API ](https://developer.github.com/v3/checks/) can be used to display validation results. I am not sure if it exists in GitLab.

**Comment by maxim-tschumak** [comment]
In my opinion we can **drop** the GitHub (Enterprise) integration aka "bark". We don't see much benefit for us (for now). I propose to adjust @roxspring 's plan to the following:

1. Implement permalinks directly in Zally #593
1. Implement GitLab integration directly in Zally, heavily inspired by existing GitHub integration code (and with the idea in mind of how we can reuse parts of the code to implement GitHub integration)
1. Create an issue for GitHub integration (with a short description of how to implement)

In this case, @roxspring, you would be able to go faster with the implementation of the desired feature and we can get rid of the unused code.

**Comment by vadeg** [comment]
@maxim-tschumak I do not agree about no benefits for us. Proper GitHub integration will bring a lot of benefits for our review process. 

A brief look at GitLab & GitHub API shows that they do not have so much in common.

For example GitHub has a [statues](https://developer.github.com/v3/repos/statuses/) and [Checks API](https://developer.github.com/v3/checks/) which can be used for notifying about API review status from Zally.

I have not found anything similar in GitLab except that GitLab CI/CD runner can attach some reports to merge requests. Maybe a special GitLab service should be implemented to support reports for merge requests. GitLab [has a plans](https://gitlab.com/gitlab-org/gitlab-ce/issues/46145) to introduce Checks API similar to what GitHub has. They had a similar [ticket before](https://gitlab.com/gitlab-org/gitlab-ce/issues/22214) but it was closed because no one needs it.

@roxspring do you have some ideas how you would integrate Zally with GitLab?

In general, I think Zally itself has nothing to do with GitLab or GitHub. The only information needed by these services is API review result. The only operations needed are send specific file (or link) to Zally and get review result back. All of these things can be done outside of Zally itself. This information can be retrieved via Zally API so there are no reasons to have Gitlab/GitHub-related code in Zally code base.

More on that, even integration with GitHub might be different. For example, some project wants to have an pull request being able to be approved by set of people, some might have automated approval and have just status check and etc. And still nothing common with Zally except requesting an API review statuses.

I think it was a correct decision to put GitHub integration into a separate module and I would go in the same way with GitLab integration. Maybe even more - move them into a separate projects like `zally-github` and `zally-gitlab`.

In general I think it should be something like this
```
+-------------------+                 +-----------------+                      +-----------------+
|  GitHub / GitLab  |                 | GH/GL Zally Tool|   -> API Definition  | Zally           |
|                   | +-------------> |                 | +--------------------+                 |
+-------------------+                 +-----------------+    <- Review Status  +-----------------+
```

**Comment by vadeg** [comment]
@maxim-tschumak 

> I'm just thinking if it makes sense for Zally server to be able to function without a persistence

You're right. It does not make sense when permalinks will be in place, but Zally can work with in-memory HSQLDB since 2017. No need to a separate database at all, if it is the case.

**Comment by roxspring** [comment]
GitLab offers [Commit Status API](https://docs.gitlab.com/ee/api/commits.html#commit-status) very similar to the GitHub status API, as far as I can see and, to me, clearly sufficient to match the current GitHub integration. I haven't looked at GitHub checks API or any equivalents that GitLab may or may not offer. I'm not familiar with further future plans for the GitHub integration outside of this epic.

From an architecture purity perspective, I totally agree that the integrations are a separate responsibility from linting itself, and spitting into two services makes sense. Indeed, if GitHub and GitLab related functionality diverge then there's a reasonable argument to further split those integrations into separate services too. I can even imagine stats and permalinks being hived off into separate microservices on the same grounds. If the system was bigger and being actively used and maintained more widely then I'm sure I'd be strongly in favour of this approach. I hope Zally receives that growth and we can return to this conversation in the context of splitting Zally into separate services in the future.

My arguments for combining at this stage are simply pragmatic. The project is still fairly small, and it's a pretty small group of us maintaining it. GitHub integration is already unused and silently falling behind as Zally and it's infrastructure is evolved. Permalinks have effectively been implemented already, but outside of Zally such that they aren't accessible to many Zally users - likely leading to permalinks being re-implemented in Zally and ultimately duplicating effort which could have been better spent. For now, the GitHub and GitLab integrations seem to be very closely aligned and I expect would likely each benefit from improvements to shared code and infrastructure. (Also, and this is possibly a personal failing, while I understand the theory of shared-nothing microservices each maintaining local copies of state, the practicalities of duplicated code and data just upset me - e.g. GHE integration and others maintaining separate Zally clients and potentially duplicating permalinks functionality).

Supporting Zally in both persistent and non-persistent configurations sounds nice in theory but, to me, not worth much time and energy. I only know of two Zally deployments: ours _finally_ has persistence properly configured and I suspect yours at Zalando has too. That also means that 100% of known deployments have aspirations of integration with SCM/CI - a percentage I don't imagine changing much as Zally is deployed more widely. IMHO it doesn't serve us well to imagine Zally as totally isolated with nothing to do with SCM/CI.

**Comment by vadeg** [comment]
Thank you @maxim-tschumak and @roxspring! Just couple of comments.

> Are you OK with throwing the unused code away and giving GitLab integration a try as a part of the Zally server?

I am totally fine with throwing away unused code, of course :) I am not OK with having GL/GH integration directly in Zally instead of having a separate component, but I agree with you both - let's try with GitLab first (at least @roxspring will use it) then will see do we need to separate it or not.

> And having an extra service with a persistence is an effort we can avoid now, from code-maintaining and operations perspective.

Probably I do not have a full picture with GH/GL integration, but what for do we need a persistence there? I thought it might work as a proxy between Zally and GL/GH without persistence at all because the only thing needed is a permalink to API review which will be managed by Zally.

> Supporting Zally in both persistent and non-persistent configurations sounds nice in theory but, to me, not worth much time and energy. 

We had this option already in place. For example, if someone wants to use Zally as a service which does only validation without keeping reports and permalinks Zally can be deployed with in-memory database. In can be deployed even with an embedded database which will store everything on disk for use cases where user do not want to setup a separate database. Nothing to invest here, actually :)

**Comment by maxim-tschumak** [comment]
> Probably I do not have a full picture with GH/GL integration, but what for do we need a persistence there?

A persistence for the review results, This is, of course, not needed if the GL/GH integration is only a proxy. In any case, we would need another deployment artifact, deployment configuration, etc (operational overhead).


In general: great that we've found a consensus :) Let's move forward!

**Comment by vadeg** [comment]
According to the list of tasks there is no more tasks left. I am closing this epic.
