### ISSUE TITLE
[Rule Sets] 2. Core Interfaces

### ISSUE THREAD

**Issue by maxim-tschumak** [zalando/zally#559]
## Epic: [Rule Sets](https://github.com/zalando-incubator/zally/issues/551)

**Acceptance Criteria**
- Interfaces are designed
  - Violation
  - Check
  - Rule
  - Rule Set
  - Rule Type
- Current Check implementations are refactored to implement new interfaces

**Comment by netme** [comment]
> Current Check implementations are refactored to implement new interfaces

Does this mean that everything should go to Zalando REST API package?

**Comment by maxim-tschumak** [comment]
> Does this mean that everything should go to Zalando REST API package?
I would move active checks only. The other ones can be part of the Zally package.

**Comment by roxspring** [comment]
FYI I have some ideas and proof-of-concept java code around the core interfaces - with a view to also allowing #446 to be addressed too. The ultimate idea is to allow rules to be implemented along the following lines, with violations being automatically tied to the Check, Rule & contextual location within the document:

```java
@Component
@Rule(id=101, title="Use Specific HTTP Status Codes")
public class UseSpecificHTTPStatusCodesRule {

  @Check(severity=MUST, message="Status codes should be in the range 100-599")
  public void noInventedCodes(String status, Response response) {
    if(Integer.parseInt(status)<100 || Integer.parseInt(status)>599) {
      throw new Violation();
    }
  }

  @Check(severity=SHOULD, message="Obscure status codes should be described")
  public void describeObscureCodes(String status, Response response) {
    if(Integer.parseInt(status)/100 > 10) {
      if(response.description==null) {
        throw new Violation();
      }
    }
  }

  @Check(severity=MAY, message="Enforce something else entirely)
  public void somethingAboutPathParameters(PathParameter param) {
    //TODO
  }
}
```

Hopefully by announcing this it'll force me to finally polish up the code and post it tonight!

**Comment by roxspring** [comment]
Definitely think that the existing .rule package should be split into at least abstract vs impl classes - very difficult to find your way around otherwise.

**Comment by roxspring** [comment]
Created POC for a CheckValidator which invokes @Check annotated methods as in my earlier comment. Location within swagger definition is standardised and should easily support x-zally-ignore  at arbitrary points. Ultimately it should be able to serve as a replacement for both JsonRulesValidator and SwaggerRulesValidator. Implemented in Java initially but should translate to Kotlin easily enough.

Feedback welcome!

https://github.com/roxspring/zally/tree/check-poc/server/src/main/java/de/zalando/zally/check

**Comment by maxim-tschumak** [comment]
@roxspring I really like the API: Having a Rule class and methods for the checks. I haven't yet looked at the implementation, but I think reflection is a good way to invoke the checks. Two things I want to mention:
1. We probably want to stick with Kotlin
2. I would prefer to implement the Check API change afterward - I think we have to invest more time here. The idea behind #446 is even more general.
Example: User disables Rule X on the path Y for parameter Z.

**Comment by roxspring** [comment]
@maxim-tschumak agree about (1) but it was just easier for me personally to prototype it in Java as I'm not yet fluent in Kotlin. Not totally clear what you mean for (2) though - are you asking for the changes to be ported to Kotlin before discussing further?

**Comment by roxspring** [comment]
Started on a less radical option this time.

Added a [RuleSet interface](https://github.com/roxspring/zally/blob/feature/added-rulesets/server/src/main/java/de/zalando/zally/rule/RuleSet.kt):
```
interface RuleSet {
    val id: String
    val title: String
    val url: String
}
```

Modified [Rule](https://github.com/roxspring/zally/blob/feature/added-rulesets/server/src/main/java/de/zalando/zally/rule/Rule.kt) to reference a RuleSet:
```
interface Rule {
    val ruleSet: RuleSet
    val title: String
    val violationType: ViolationType
    val url: String?
    val code: String
    val guidelinesCode: String
    val name: String
}
```

Also added a couple of @Components to implement [Zalando](https://github.com/roxspring/zally/blob/feature/added-rulesets/server/src/main/java/de/zalando/zally/rule/ZalandoRuleSet.kt) and [Zally](https://github.com/roxspring/zally/blob/feature/added-rulesets/server/src/main/java/de/zalando/zally/rule/ZallyRuleSet.kt) RuleSets and associated each rule with one of them via @Autowired constructors.

This more the start you had in mind @maxim-tschumak ?

**Comment by maxim-tschumak** [comment]
@roxspring Yes, exactly :) 
Some minor change proposals:
- Let's merge `code` and `guidelinesCode` to `Id`
- Let's remove `name` (`title` should be enough)

**Comment by roxspring** [comment]
Made those changes on my branch too: https://github.com/zalando-incubator/zally/compare/master...roxspring:feature/added-rulesets?expand=1

All this refactoring is making breaking changes at the Java API and presumably will do at the REST API and database schema level too. Is the expectation to make them in master and leave it versioned 1.0.0? Or should we stabilise these changes on a shared v2 branch?

**Comment by maxim-tschumak** [comment]
I wouldn't go for a long-living branch. I think we can avoid breaking changes if we implement 1-4 steps sequentially, as proposed in #551.
Do you have an example of a non-backward compatible change? (please keep in mind that we don't have to expose implementation details to the API consumers)

**Comment by roxspring** [comment]
The entire Rule Sets epic is breaking changes:
1. "Ignore Rules by External Ids" is a fundamental behaviour change. Old configurations will have surprising results after that change is made. I don't see how the result is affected whether this is done first vs last.
2. "Core Interfaces" can't be changed without making old code fundamentally incompatible with new code, especially when you start merging and removing fields. Assuming these changes are to show up in through REST APIs like /supported-rules then we're looking at breaking changes there too. Unless you're plan is to implement all of this using a new Rule2 interface and expose a ruleset aware REST API at /supported-rules-2, all while keeping existing interfaces and REST APIs maintained in parallel.
3. "Package Discovery" - ok this shouldn't be breaking since there's no existing functionality to break!
4. "Statistics for Rule Sets" - again I imagine it'll be difficult to maintain the existing REST API (after removing and merging fields), and certainly would expect to want a radical change to build in useful Rule Set awareness. (I could be wrong here, haven't paid much attention to stats side of things yet)

Assuming that you're applying http://semver.org logic then the basic rules are:
- We can add functionality but it forces us to at least 1.1.0
- We can remove or merge stuff but it forces us to at least 2.0.0
There may be a little wiggle room if you only want to commit to this at a REST API rather than code level too. But it's not exactly a big win if you get to remove unnecessary properties at a code level only to have to fake their existence again in the REST API.

Would be good to understand where you think the compatibility lines should be drawn. I can just about see how we can add Rule Sets & maybe Checks can be added in a 1.1.0 but cleaning `id` vs `code` vs `guideline` and `name` vs `title` surely implies we're working towards a 2.0.0.

**Comment by maxim-tschumak** [comment]
I agree with the things you've pointed out. In my opinion, all the Java interfaces and configurations are part of the internal interfaces which don't have to stay backward compatible. The only public interface of the server component is the RESTful API.

Regarding the RESTful API endpoints: as you mentioned, we can either go for a new minor version by extending the existing API (without breaking changes) or design a new major version. IMHO, both options are valid and can be implemented.

> Would be good to understand where you think the compatibility lines should be drawn. I can just about see how we can add Rule Sets & maybe Checks can be added in a 1.1.0 but cleaning id vs code vs guideline and name vs title surely implies we're working towards a 2.0.0.

I believe, what you mean here is the compatibility of the internal interfaces (am I right?). If yes, it's OK to not be backward compatible at all and do all the refactorings we want to implement. The reasoning is very simple: besides your organization and Zalando, there are no known installations of Zally server.

**Comment by roxspring** [comment]
> I agree with the things you've pointed out. In my opinion, all the Java interfaces and configurations are part of the internal interfaces which don't have to stay backward compatible. The only public interface of the server component is the RESTful API.

For now, while there are only 1 or 2 installations of Zally then you're right: the internal interfaces don't have to stay backward compatible. But I'd argue that the same is true of the RESTful API too. Longer term, in an imaginary future where 100s of Zally servers are in use as the linter of choice for swagger users, then we need to treat both the RESTful API *and* the Java API as public interfaces with a backwards compatibility commitment - otherwise people potentially need to re-implement their custom rules each time they upgrade Zally and will quickly become frustrated.  (Note that "Java API" here means only the bit that custom rule developers need to use - everything else can be changed as needed)

---

Bringing all this back to practicalities, way above we were discussing the Java level API and you suggested:
> Let's merge code and guidelinesCode to Id

I presume you're aware that the `code` shows up in the REST API:
```
{
  "rules": [
    {
      "title": "OpenAPI 2.0 schema",
      "type": "MUST",
      "url": "https://wiki.int.corefiling.com/platform/APIGuidelines/#101",
      "code": "M000",
      "is_active": true
    },
    ...
  ]
}
```

And so replacing `code` with `id` either means that we use different terminology at the REST vs Java levels, or that this makes for a REST change. Seems to me that using different layers using different terminology for the same concepts is madness and so both Java and REST APIs should be affected by this change.

Assuming we're on the same page here then I think the conclusion is that if I open a PR with these backwards incompatible (at the Java & REST level) but consistent (between server, cli & web-ui) changes, I should hope to merge it into the master branch and leave the version as 1.0.0. Right?

**Comment by maxim-tschumak** [comment]
>  Longer term, in an imaginary future where 100s of Zally servers are in use as the linter of choice for swagger users, [..]

:heart: 

> [..] the internal interfaces don't have to stay backward compatible. But I'd argue that the same is true of the RESTful API too.

Of course not!

> [..] different layers using different terminology for the same concepts is madness [..]

Yes, it should be consistent. But please keep in mind that it can also be a great idea to decouple internal Java API and resource representations in the RESTful API. Here is an incomplete example:

`Java API (models, interfaces) = {RuleSet, Rule, Check, CheckResult}`
`RESTful API (resources) = {Violations, ReviewStatistics, SupportedRule}`

By having this kind of segregation we make the software easier to change and evolve: it's easier to adjust only one part - e.g. external RESTful API - without having to adjust the internal (Java/Kotlin) API. This can also potentially stop propagation of a breaking change between the two kinds of interfaces.

> Assuming we're on the same page here then I think the conclusion is that if I open a PR with these backwards incompatible (at the Java & REST level) but consistent (between server, cli & web-ui) changes, I should hope to merge it into the master branch and leave the version as 1.0.0. Right?

I think there are 3 questions in this paragraph. Here is my opinion on them:
1. Should the changes be consistent? - **Yes**, always :)
2. Can we make breaking changes? - **Yes**, in Java API and RESTful API
3. Should we use semantic versioning and reflect the changes in Java package and RESTful API versions? - **Yes**. I would go with `2.0.0` for the JVM artifact and `2.0.0` for the RESTful API (if we break `1.1.1`)


@roxspring Thank you for starting this discussion. It's very helpful for the Zally project!

**Comment by roxspring** [comment]
Not sure we're on exactly the same page yet but I'd like to get things moving forward...

Within the next week I'll open a PR adding RuleSets and merging `code` and `guideline` into `id` at the Java level. Possibly it'll also address Check and CheckResult, although I'm concerned that'll be too big a change to review in one shot. I'll leave the REST API unchanged and we can dodge the versioning question for now. 

Let me know if you see a problem with this approach.

**Comment by tkrop** [comment]
> But please keep in mind that it can also be a great idea to decouple internal Java API and resource representations in the RESTful API.

I support this approach:

1. to provide compatibility with the original API while refactoring the core,
2. because implementation details should not escape into the API.

It is a great thing to have an abstraction that allows to keep implementation and API consistent. In an ideal world designs would always be this way, but mostly we have to travel a long way to reach this state. In between living with this differences can provide a great advantage as it allows to keep APIs stable with moderate costs.

**Comment by roxspring** [comment]
Think this can be closed now @maxim-tschumak:

- Interfaces are designed
  - Violation - Simple data class comprising a description applying to some locations.
  - Check - Annotation on methods with (mandatory) severity parameter
  - Rule - Annotation on rule classes with ruleSet/id/title/severity
  - Rule Set - Class consisting of id, title; owns url construction.
  - Rule Type - Enum renamed to Severity
- Current Check implementations are refactored to implement new interfaces - all zally and zalando guidelines converted to `@Rule` and `@Check` annotated classes.

**Comment by maxim-tschumak** [comment]
The only thing that I'm not 100% happy with is the fact that each rule implementation has to do 2 things:
1. Be annotated with `@Rule`, and
2. Extend the `AbstractRule` class.

Can we improve this? @netme @mkulak - what do the Kotlin experts think? :)

**Comment by roxspring** [comment]
Hmmm... I'm pretty sure there's no hard requirement to extend AbstractRule any more, though possibly the hashCode() / equals() are important. Will try to confirm/deny this evening.

I did wonder about allowing some of the annotated attributes to be optional and implementing some defaulting logic in the RuleManager / RuleValidator:
- Check.severity defaults to owning Rule.severity
- Rule.id defaults to Rule.class.simpleName (our own in-house convention, seems effective)
- Rule.title defaults to titleCaseOf(Rule.class.simpleName) (again would likely suit me in-house)

But that's mostly about simplifying in-house rule definitions rather than general purpose needs. Otherwise am interested to hear what others think!
