### ISSUE TITLE
Checks for Zalando Rule 143 are too Strict

### ISSUE THREAD

**Issue by maxim-tschumak** [zalando/zally#741]
The Rule implementation has to check:
- [x] If first path segment is a parameter (is not stated explicitly in the rule, it's common sense )

**Comment by roxspring** [comment]
I always thought that "Every second path level must be a path parameter" was an odd interpretation of this rule. Personally I'd aim for a "Every path-parameter must be proceeded by a non-path-parameter" rather than only check the first segment - although I can see that checking the first segment likely addresses most cases.

The guideline doesn't seem to say anything about the use of parameters called `id` though... that seems an oddly specific check to add here.

**Comment by maxim-tschumak** [comment]
> I always thought that "Every second path level must be a path parameter" was an odd interpretation of this rule.

You a right - it was a misinterpretation

> The guideline doesn't seem to say anything about the use of parameters called id though... that seems an oddly specific check to add here.

I gave it another thought - `id` query parameter is plausible for "batch" requests (give me resources with the ids: x,y,z) - I'll remove this check
