### ISSUE TITLE
More flexible whitelist for PluralizeResourceNamesRule

### ISSUE THREAD

**Issue by roxspring** [zalando/zally#780]
Generally, I like the idea of `PluralizeResourceNamesRule` but internally we have it disabled due to fear of too many "false positives":

1. We have a standard `GET /status` API on each service used for basic health checks. Clearly, the resource here is not plural but we want to accept it anyway. 

2. We also have a whole bunch of `POST /things/{id}/action` APIs which may not be ideal from a RESTful point of view but are a regular solution all the same and we're willing to live with them. 

3. I'm in constant fear that we're going to find terms which the `PlingStemmer` doesn't correctly identify as plurals and I don't really want to open an IDE for every exception we need to make.

Problem (1) can be addressed by configuring `whitelist_prefixes` and that suggests that adding a `whitelist_suffixes` configuration might be a reasonable solution to (2). Given that elsewhere we've become comfortable using regex in configurations I'm tempted to suggest we just use a single `whitelist` of regexes `^/status/`, `/action$` instead. Thoughts?

Problem (3) screams out for a configurable whitelist of plural terms. What I'm not certain about is whether this should be specific to `PluralizeResourceNamesRule` or a whitelist shared with `PluralizeNamesForArraysRule` and future uses of `isPlural(String)`?

**Comment by tkrop** [comment]
I would vote for adding a single `whitelist`-regexp for customization.

I'm not convinced that, the pluralization rule itself should be configured via a file. In the first place we should invest into applying a good algorithm, maybe by searching a feasible OS-library. If we need an to add exceptions, because the word is heavily used, it either very company specific and should be handled by the `whitelist`-regexp, or it is so common that we should introduce it as extension into the implemented algorithm. To foster the discussion in the second case, I would like to stick to hardcoding this extensions.
