### ISSUE TITLE
Implement generic test pattern to catch NPEs, etc in all rules.

### ISSUE THREAD

**Issue by tkrop** [zalando/zally#832]
While moving to OpenAPI 3.0 and migrating to Kotlin we had repeated problems with NPEs and SOEs in rules. May be we need a generic test pattern to detect some generally happening programmer mistakes for incomplete OpenAPI specifications. Such a task will pay off the more rules Zally provides.

**Comment by roxspring** [comment]
Anybody know if there's a way to persuade Kotlin / Idea that e.g. `OpenAPI.paths` should have a signature of `Map<String, PathItem>?` rather than the `Map<String, PathItem>` without modifying the upstream Java sources? Feels like that would go a long way to addressing the NullPointerException problem.

Don't have any great suggestion for addressing StackOverflowExceptions (presumably what's meant by SOE above).

**Comment by tkrop** [comment]
We have fixed another generic issue. While doing so we discovered a minimal strategy to solve this issue (see [my comment](https://github.com/zalando/zally/pull/835/files#r217303561)). The basic concept is to create a minimal API specification that covers all important elements and step by replace leave values against `null` and remove leaves. A parameterized test will with all resulting APIs allows discovery all potential NPE reason.

**Comment by roxspring** [comment]
Are there thoughts to do anything more with this issue or should we just close it?

**Comment by maxim-tschumak** [comment]
The idea @tkrop has mentioned is not implemented yet (a test which executes all rules against API specs with various null values).

**Comment by roxspring** [comment]
As of #867 I think I've implemented @tkrop's idea (which I kept overlooking) so suspect this is closable now.
